In [1]:
# Лабораторна робота №1 (варіант 2)
# Автор: Байков Олександр Сергійович ФІТ 4-11
# На парі був


In [2]:
import numpy as np

In [3]:
# Завдання 1
# Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
z1 = np.arange(1, 21)
print("Завдання 1:\n", z1, "\n")

Завдання 1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 



In [4]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими натуральними числами та виведіть його значення.
z2 = np.random.randint(1, 100, (3, 3))
print("Завдання 2:\n", z2, "\n")

Завдання 2:
 [[76  5 57]
 [43 52 29]
 [90 98 85]] 



In [5]:
# Завдання 3
# Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
z3 = np.random.uniform(-1, 1, (5, 5))
print("Завдання 3:\n", z3, "\n")

Завдання 3:
 [[-0.32708798  0.57991614 -0.56588671 -0.66956454  0.92345241]
 [ 0.96737356 -0.76806428 -0.17366191 -0.77581094 -0.34961116]
 [-0.59889865  0.06664717  0.48350953 -0.45344399 -0.51189842]
 [ 0.42004459 -0.48594627 -0.95715391 -0.30655293 -0.33496079]
 [-0.50523926  0.58865657 -0.47858238  0.91151587  0.91963698]] 



In [6]:
# Завдання 4
# Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє значення елементів.
z4 = np.random.rand(5, 5)
print("Завдання 4 (матриця):\n", z4)
print("Середнє значення:", np.mean(z4), "\n")

Завдання 4 (матриця):
 [[0.04278872 0.69222305 0.6590666  0.75262317 0.52717819]
 [0.78697625 0.07015824 0.97266305 0.49227769 0.94057571]
 [0.69463999 0.02408701 0.86701573 0.3888782  0.82975856]
 [0.49208203 0.6804958  0.57800019 0.88034956 0.61100442]
 [0.69730164 0.69844771 0.22365342 0.48205699 0.12501583]]
Середнє значення: 0.5683727102453225 



In [7]:
# Завдання 5
# Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a5 = np.random.randint(-10, 11, 5)
b5 = np.random.randint(-10, 11, 5)
print("Завдання 5:")
print("a:", a5)
print("b:", b5)
print("Додавання:", a5 + b5)
print("Віднімання:", a5 - b5)
print("Множення:", a5 * b5, "\n")

Завдання 5:
a: [-7 -7 -6  8 -9]
b: [-6 -4 -4 -3  4]
Додавання: [-13 -11 -10   5  -5]
Віднімання: [ -1  -3  -2  11 -13]
Множення: [ 42  28  24 -24 -36] 



In [8]:
# Завдання 6
# Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та знайдіть їх добуток.
A6 = np.random.uniform(3, 10, (2, 2))
B6 = np.random.uniform(3, 10, (2, 2))
C6 = np.dot(A6, B6)
print("Завдання 6:")
print("A:\n", A6)
print("B:\n", B6)
print("A*B:\n", C6, "\n")

Завдання 6:
A:
 [[9.42366781 4.6100734 ]
 [7.39064982 7.38803194]]
B:
 [[7.44367854 5.59919461]
 [6.09205331 5.66834203]]
A*B:
 [[ 98.2315667   78.89642279]
 [100.02190594  83.25957864]] 



In [9]:
# Завдання 7
# Створіть дві матриці 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
A7 = np.random.randint(1, 6, (2, 3))
B7 = np.random.randint(1, 6, (3, 2))
C7 = np.dot(A7, B7)
print("Завдання 7:")
print("A:\n", A7)
print("B:\n", B7)
print("A*B:\n", C7, "\n")

Завдання 7:
A:
 [[5 3 4]
 [2 2 5]]
B:
 [[1 5]
 [4 4]
 [1 3]]
A*B:
 [[21 49]
 [15 33]] 



In [10]:
# Завдання 8
# Створіть матрицю 3x3, заповніть її випадковими цілими числами від 1 до 12 та знайдіть її обернену матрицю.
A8 = np.random.randint(1, 13, (3, 3))
invA8 = np.linalg.inv(A8)
print("Завдання 8:\nA:\n", A8)
print("A^(-1):\n", invA8, "\n")

Завдання 8:
A:
 [[ 9  4  6]
 [ 6  6  3]
 [12  7  4]]
A^(-1):
 [[-0.02857143 -0.24761905  0.22857143]
 [-0.11428571  0.34285714 -0.08571429]
 [ 0.28571429  0.14285714 -0.28571429]] 



In [11]:
# Завдання 9
# Створіть матрицю 4x4, заповніть її випадковими дійсними числами в діапазоні від -8 до 8 та транспонуйте її.
A9 = np.random.uniform(-8, 8, (4, 4))
print("Завдання 9:\nA:\n", A9)
print("A^T:\n", A9.T, "\n")

Завдання 9:
A:
 [[-6.94139696 -1.35210101 -4.10766343 -2.39467006]
 [-6.42805948  0.45186532  7.38773641 -0.59596566]
 [-7.55184683  4.30926401  4.1517053   7.09455365]
 [ 4.28765806 -1.78245474  7.00704782  0.75857259]]
A^T:
 [[-6.94139696 -6.42805948 -7.55184683  4.28765806]
 [-1.35210101  0.45186532  4.30926401 -1.78245474]
 [-4.10766343  7.38773641  4.1517053   7.00704782]
 [-2.39467006 -0.59596566  7.09455365  0.75857259]] 



In [12]:
# Завдання 10
# Створіть матрицю 3x4 та вектор 4x1, заповніть їх випадковими цілими числами від 1 до 10 та знайдіть середнє значення елементів матриці.
A10 = np.random.randint(1, 11, (3, 4))
b10 = np.random.randint(1, 11, (4, 1))
print("Завдання 10:")
print("A:\n", A10)
print("b:\n", b10)
print("Середнє значення елементів матриці A:", np.mean(A10), "\n")

Завдання 10:
A:
 [[ 1 10  2 10]
 [ 2  8  4  4]
 [ 3  8  3  1]]
b:
 [[ 4]
 [ 6]
 [ 8]
 [10]]
Середнє значення елементів матриці A: 4.666666666666667 



In [13]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
A11 = np.random.randint(1, 11, (2, 3))
b11 = np.random.rand(3, 1)
prod11 = A11.dot(b11)
print("Завдання 11 — матриця A (2x3):")
print(A11)
print("Вектор b (3x1):")
print(b11)
print("Добуток A * b (2x1):")
print(prod11)
print()

Завдання 11 — матриця A (2x3):
[[10  8  8]
 [10  9  5]]
Вектор b (3x1):
[[0.13629964]
 [0.12740994]
 [0.04884103]]
Добуток A * b (2x1):
[[2.77300415]
 [2.75389099]]



In [14]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
A12 = np.random.randint(1, 11, (3, 3))
B12 = np.random.randint(1, 11, (3, 3))
diff12 = A12 - B12
print("Завдання 12 — матриці A і B:")
print(A12)
print(B12)
print("A − B:")
print(diff12)
print()

Завдання 12 — матриці A і B:
[[ 2 10  6]
 [ 9  6  3]
 [10  3  3]]
[[ 9  3  7]
 [10  4  3]
 [ 7  7  6]]
A − B:
[[-7  7 -1]
 [-1  2  0]
 [ 3 -4 -3]]



In [15]:
# Завдання 13
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
A13 = np.random.randint(-5, 6, (3, 3))
B13 = np.random.randint(-5, 6, (3, 3))
prod13 = np.dot(A13, B13)
print("Завдання 13 — матриці A і B:")
print(A13)
print(B13)
print("A * B:")
print(prod13)
print()

Завдання 13 — матриці A і B:
[[-2  3  4]
 [ 3  5 -5]
 [-2  4  0]]
[[ 4 -2 -3]
 [-5 -4  5]
 [-1  3  4]]
A * B:
[[-27   4  37]
 [ -8 -41  -4]
 [-28 -12  26]]



In [16]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть суму елементів матриці.
A14 = np.random.randint(-5, 6, (3, 3))
sum14 = np.sum(A14)
print("Завдання 14 — матриця A:")
print(A14)
print("Сума елементів матриці A:", sum14)
print()

Завдання 14 — матриця A:
[[-4 -1  3]
 [-1  2  0]
 [-5  0  1]]
Сума елементів матриці A: -5



In [17]:
# Завдання 15
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
# що містить добуток елементів кожного рядка матриці.
A15 = np.random.rand(4, 4)
prod_rows_15 = np.prod(A15, axis=1).reshape(4, 1)
print("Завдання 15 — матриця A (4x4):")
print(A15)
print("Вектор-стовпчик (добуток рядків):")
print(prod_rows_15)

Завдання 15 — матриця A (4x4):
[[0.16201176 0.60675818 0.6588968  0.74920076]
 [0.41158748 0.33254677 0.62874843 0.81600821]
 [0.61619653 0.27436563 0.62238939 0.37113216]
 [0.939326   0.41200534 0.6033821  0.55584499]]
Вектор-стовпчик (добуток рядків):
[[0.04852637]
 [0.07022412]
 [0.03905168]
 [0.12979719]]


In [ ]:
# Висновок:
# У цій лабораторній роботі виконано основні операції з масивами та матрицями у середовищі Google Colab з використанням бібліотеки NumPy