In [ ]:
# Лабораторна робота №1 Частина 2.
# Автор: Байков Олександр Сергійович ФІТ 4-11
# На парі  був


In [2]:
import numpy as np

In [8]:
# 1. Задати вектор, що складається з перших п'яти натуральних чисел
vector = np.array([1, 2, 3, 4, 5])
print("Вектор:", vector)


Вектор: [1 2 3 4 5]


In [9]:
# 2. Транспонувати вектор
v1 = np.matrix(vector)
v2 = v1.T
print("Транспонований вектор:\n", v2)

Транспонований вектор:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
# 3. Напишіть функцію, яка перетворює вектор у зворотньому порядку
v_reversed = vector[::-1]
print("Вектор у зворотньому порядку:", v_reversed)


Вектор у зворотньому порядку: [5 4 3 2 1]


In [11]:
# 4. Обчислити середнє значення вектора
print("Середнє значення:", np.mean(vector))


Середнє значення: 3.0


In [12]:
# 5. Знайдіть найбільший і найменший елемент вектора
print("Мінімум:", np.min(vector))
print("Максимум:", np.max(vector))

Мінімум: 1
Максимум: 5


In [13]:
# 6. Обчисліть скалярний добуток (dot product) двох векторів
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Скалярний добуток:", np.dot(v1, v2))
print("Покрокове множення:", v1*v2)

Скалярний добуток: 32
Покрокове множення: [ 4 10 18]


In [14]:
# 7. Напишіть функцію, яка нормалізує вектор(зводить до одиничної довжини)
norm_v = np.linalg.norm(vector)
print("Норма вектора:", norm_v)
print("Нормалізований вектор:", vector/norm_v)

Норма вектора: 7.416198487095663
Нормалізований вектор: [0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


In [15]:
# 8. Задайте два вектори. Визначте, чи є вони ортогональними
v3 = np.array([1, 0, 0])
v4 = np.array([0, 1, 0])
print("Ортогональні?", np.dot(v3, v4) == 0)

Ортогональні? True


In [16]:
# 9. Визначте унікальні елементи вектора
v = np.array([1, 2, 3, 2, 4, 5, 3])
print("Унікальні елементи:", np.unique(v))

Унікальні елементи: [1 2 3 4 5]


In [17]:
# 10. Знайти вектори
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Віднімання:", v1-v2, v2-v1)
print("Додавання:", v1+v2, v2+v1)
print("Множення:", v1*v2, v2*v1)
print("Ділення:", v1/v2, v2/v1)

Віднімання: [-3 -3 -3] [3 3 3]
Додавання: [5 7 9] [5 7 9]
Множення: [ 4 10 18] [ 4 10 18]
Ділення: [0.25 0.4  0.5 ] [4.  2.5 2. ]


In [18]:
# 11. Перевірити, чи дорівнює довжина вектора 5
length_check = np.isclose(np.linalg.norm(vector), 5)
print("Довжина ≈ 5?", length_check)

Довжина ≈ 5? False


In [19]:
# 12. Задати матрицю, заповнену випадковими числами
a = np.random.randint(0, 11, (3, 3))
print("Випадкова матриця:\n", a)

Випадкова матриця:
 [[9 2 5]
 [0 4 2]
 [0 4 0]]


In [20]:
# 13. Обчислити визначення матриці
print("Визначник матриці:", np.linalg.det(a))

Визначник матриці: -72.0


In [21]:
# 14. Обчислити визначник матриці (обернена матриця)
print("Обернена матриця:\n", np.linalg.inv(a))

Обернена матриця:
 [[ 0.11111111 -0.27777778  0.22222222]
 [ 0.          0.          0.25      ]
 [-0.          0.5        -0.5       ]]


In [22]:
# 15. Розв'яжіть систему оінійних рівнянь А*х=b, де А - матриця коефіцієнтів, b - вектор вільних членів
A = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])
x = np.linalg.solve(A, b)
print("Розв'язок системи:", x)

Розв'язок системи: [0.38888889 1.83333333 0.22222222]


In [23]:
# 16. Множення двох матриць
print("Множення матриць (вектор):", np.dot(A, b))
B = np.array([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
A2 = np.array([[1, 3, -4], [0, 2, -3]])
print("Множення матриць:\n", np.dot(A2, B))

Множення матриць (вектор): [-2 -6 16]
Множення матриць:
 [[-1  4  7]
 [-5  0  1]]


In [25]:
# 17. Транспонування матриць
print("Транспонування A2:\n", A2.T)
print("Транспонування B:\n", B.T)


Транспонування A2:
 [[ 1  0]
 [ 3  2]
 [-4 -3]]
Транспонування B:
 [[5 2 3]
 [3 3 2]
 [4 5 3]]


In [26]:
# 18. Перевірка симетричності матриць
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2,2,2]])
print("Симетрична?", np.allclose(matrix, matrix.T))

Симетрична? True


In [27]:
# 19. Обчислення сліду матриці
print("Слід матриці:", np.trace(matrix))

Слід матриці: 6


In [28]:
# 20. Дії з матрицями
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])
print("Додавання:\n", np.add(a, b))
print("Віднімання:\n", np.subtract(a,b))
print("Множення:\n", np.multiply(a, b))
print("Ділення:\n", np.divide(a, b))

Додавання:
 [[ 6  8]
 [10 12]]
Віднімання:
 [[-4 -4]
 [-4 -4]]
Множення:
 [[ 5 12]
 [21 32]]
Ділення:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
# 21. Піднесення матриці до ступення
print("Матриця у квадраті:\n", np.linalg.matrix_power(a, 2))

Матриця у квадраті:
 [[ 7 10]
 [15 22]]


In [30]:
# 22. Сортування рядків або стовпців мамтриці
b2 = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print("Сортування по стовпцях:\n", np.sort(b2, axis=0))
print("Сортування по рядках:\n", np.sort(b2, axis=1))
print("Сортування всіх елементів:\n", np.sort(b2, axis=None))

Сортування по стовпцях:
 [[2 2 3]
 [3 3 4]
 [5 3 5]]
Сортування по рядках:
 [[3 4 5]
 [2 3 5]
 [2 3 3]]
Сортування всіх елементів:
 [[2 2 3 3 3 3 4 5 5]]


In [32]:
# 23. Підрахувати суму елементів кожного рядка матриці. Відповіді записати у вигляді вектора-стовпчика
row_sums = np.sum(a, axis=1).reshape(-1,1)
print("Сума елементів рядків:\n", row_sums)

Сума елементів рядків:
 [[3]
 [7]]


In [ ]:
# Висновок. У роботі виконано основні операції з векторами та матрицями в Python, включно з обчисленнями, транспонуванням та розв’язанням систем рівнянь.