In [ ]:
# Лабораторна робота №1 (варіант 2)
# Автор: Байков Олександр Сергійович ФІТ 4-11
# На парі не був


In [ ]:
import numpy as np

In [ ]:
# Завдання 1
# Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
z1 = np.arange(1, 21)
print("Завдання 1:\n", z1, "\n")

Завдання 1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 



In [ ]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими натуральними числами та виведіть його значення.
z2 = np.random.randint(1, 100, (3, 3))
print("Завдання 2:\n", z2, "\n")

Завдання 2:
 [[52 93 15]
 [72 61 21]
 [83 87 75]] 



In [ ]:
# Завдання 3
# Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
z3 = np.random.uniform(-1, 1, (5, 5))
print("Завдання 3:\n", z3, "\n")

Завдання 3:
 [[ 0.27887939 -0.264417   -0.08587963 -0.42411969 -0.13625899]
 [-0.25385105  0.95770777  0.90606548 -0.55501371 -0.08496045]
 [ 0.42981786 -0.86225755  0.12067399 -0.87840688 -0.22724586]
 [-0.26418597  0.78070651  0.57464012 -0.86297638 -0.48015925]
 [-0.62555007  0.68916595  0.06561926  0.20603019 -0.81902641]] 



In [ ]:
# Завдання 4
# Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє значення елементів.
z4 = np.random.rand(5, 5)
print("Завдання 4 (матриця):\n", z4)
print("Середнє значення:", np.mean(z4), "\n")

Завдання 4 (матриця):
 [[0.12063139 0.75997822 0.00576577 0.56050805 0.54566447]
 [0.94773317 0.37831228 0.24836282 0.64416268 0.89103919]
 [0.41997235 0.43579723 0.32637678 0.00576123 0.36585824]
 [0.34490213 0.78031871 0.10053316 0.44105111 0.90278219]
 [0.1506128  0.78462169 0.2328633  0.56720349 0.82738715]]
Середнє значення: 0.47152798398144286 



In [ ]:
# Завдання 5
# Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a5 = np.random.randint(-10, 11, 5)
b5 = np.random.randint(-10, 11, 5)
print("Завдання 5:")
print("a:", a5)
print("b:", b5)
print("Додавання:", a5 + b5)
print("Віднімання:", a5 - b5)
print("Множення:", a5 * b5, "\n")

Завдання 5:
a: [ 8 -8 -1 -2  9]
b: [-5 -2  9  8 -9]
Додавання: [  3 -10   8   6   0]
Віднімання: [ 13  -6 -10 -10  18]
Множення: [-40  16  -9 -16 -81] 



In [ ]:
# Завдання 6
# Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та знайдіть їх добуток.
A6 = np.random.uniform(3, 10, (2, 2))
B6 = np.random.uniform(3, 10, (2, 2))
C6 = np.dot(A6, B6)
print("Завдання 6:")
print("A:\n", A6)
print("B:\n", B6)
print("A*B:\n", C6, "\n")

Завдання 6:
A:
 [[4.72323403 4.62475461]
 [4.7074965  4.66204156]]
B:
 [[6.55432525 4.23327579]
 [6.41599374 7.10840324]]
A*B:
 [[60.63000866 52.86937291]
 [60.76609262 53.06780229]] 



In [ ]:
# Завдання 7
# Створіть дві матриці 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
A7 = np.random.randint(1, 6, (2, 3))
B7 = np.random.randint(1, 6, (3, 2))
C7 = np.dot(A7, B7)
print("Завдання 7:")
print("A:\n", A7)
print("B:\n", B7)
print("A*B:\n", C7, "\n")

Завдання 7:
A:
 [[1 4 4]
 [3 5 4]]
B:
 [[2 1]
 [2 1]
 [4 5]]
A*B:
 [[26 25]
 [32 28]] 



In [ ]:
# Завдання 8
# Створіть матрицю 3x3, заповніть її випадковими цілими числами від 1 до 12 та знайдіть її обернену матрицю.
A8 = np.random.randint(1, 13, (3, 3))
invA8 = np.linalg.inv(A8)
print("Завдання 8:\nA:\n", A8)
print("A^(-1):\n", invA8, "\n")

Завдання 8:
A:
 [[11  7  1]
 [ 2 11  7]
 [ 3  3  4]]
A^(-1):
 [[ 0.07255521 -0.07886435  0.11987382]
 [ 0.04100946  0.12933754 -0.23659306]
 [-0.0851735  -0.03785489  0.33753943]] 



In [ ]:
# Завдання 9
# Створіть матрицю 4x4, заповніть її випадковими дійсними числами в діапазоні від -8 до 8 та транспонуйте її.
A9 = np.random.uniform(-8, 8, (4, 4))
print("Завдання 9:\nA:\n", A9)
print("A^T:\n", A9.T, "\n")

Завдання 9:
A:
 [[-3.75726774  3.92480472 -1.26268313  6.65277986]
 [ 5.56586621  4.3986446  -0.73174251  7.19103591]
 [ 5.19426588  1.14705655  2.59083461 -5.69722023]
 [ 7.92574406  7.57701279  1.8591234   4.24947029]]
A^T:
 [[-3.75726774  5.56586621  5.19426588  7.92574406]
 [ 3.92480472  4.3986446   1.14705655  7.57701279]
 [-1.26268313 -0.73174251  2.59083461  1.8591234 ]
 [ 6.65277986  7.19103591 -5.69722023  4.24947029]] 



In [ ]:
# Завдання 10
# Створіть матрицю 3x4 та вектор 4x1, заповніть їх випадковими цілими числами від 1 до 10 та знайдіть середнє значення елементів матриці.
A10 = np.random.randint(1, 11, (3, 4))
b10 = np.random.randint(1, 11, (4, 1))
print("Завдання 10:")
print("A:\n", A10)
print("b:\n", b10)
print("Середнє значення елементів матриці A:", np.mean(A10), "\n")

Завдання 10:
A:
 [[ 1  9  7  2]
 [ 5  4 10  3]
 [ 8  3  2  6]]
b:
 [[9]
 [5]
 [5]
 [6]]
Середнє значення елементів матриці A: 5.0 



In [ ]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
A11 = np.random.randint(1, 11, (2, 3))
b11 = np.random.rand(3, 1)
prod11 = A11.dot(b11)
print("Завдання 11 — матриця A (2x3):")
print(A11)
print("Вектор b (3x1):")
print(b11)
print("Добуток A * b (2x1):")
print(prod11)
print()

Завдання 11 — матриця A (2x3):
[[8 5 4]
 [8 8 3]]
Вектор b (3x1):
[[0.02058449]
 [0.96990985]
 [0.83244264]]
Добуток A * b (2x1):
[[ 8.34399578]
 [10.42128269]]



In [ ]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
A12 = np.random.randint(1, 11, (3, 3))
B12 = np.random.randint(1, 11, (3, 3))
diff12 = A12 - B12
print("Завдання 12 — матриці A і B:")
print(A12)
print(B12)
print("A − B:")
print(diff12)
print()

Завдання 12 — матриці A і B:
[[ 6  2  5]
 [ 1 10  6]
 [ 9  1 10]]
[[3 7 4]
 [9 3 5]
 [3 7 5]]
A − B:
[[ 3 -5  1]
 [-8  7  1]
 [ 6 -6  5]]



In [ ]:
# Завдання 13
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
A13 = np.random.randint(-5, 6, (3, 3))
B13 = np.random.randint(-5, 6, (3, 3))
prod13 = np.dot(A13, B13)
print("Завдання 13 — матриці A і B:")
print(A13)
print(B13)
print("A * B:")
print(prod13)
print()

Завдання 13 — матриці A і B:
[[ 3  1 -4]
 [-2  3 -4]
 [ 4  3  4]]
[[-1 -4 -2]
 [ 1  2 -3]
 [-5 -2 -4]]
A * B:
[[ 18  -2   7]
 [ 25  22  11]
 [-21 -18 -33]]



In [ ]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть суму елементів матриці.
A14 = np.random.randint(-5, 6, (3, 3))
sum14 = np.sum(A14)
print("Завдання 14 — матриця A:")
print(A14)
print("Сума елементів матриці A:", sum14)
print()

Завдання 14 — матриця A:
[[ 2 -2 -4]
 [ 0  0  4]
 [-2  0 -4]]
Сума елементів матриці A: -6



In [ ]:
# Завдання 15
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
# що містить добуток елементів кожного рядка матриці.
A15 = np.random.rand(4, 4)
prod_rows_15 = np.prod(A15, axis=1).reshape(4, 1)
print("Завдання 15 — матриця A (4x4):")
print(A15)
print("Вектор-стовпчик (добуток рядків):")
print(prod_rows_15)

Завдання 15 — матриця A (4x4):
[[0.77513282 0.93949894 0.89482735 0.59789998]
 [0.92187424 0.0884925  0.19598286 0.04522729]
 [0.32533033 0.38867729 0.27134903 0.82873751]
 [0.35675333 0.28093451 0.54269608 0.14092422]]
Вектор-стовпчик (добуток рядків):
[[0.38961907]
 [0.0007231 ]
 [0.02843538]
 [0.00766506]]


In [ ]:
# Висновок:
# У цій лабораторній роботі виконано основні операції з масивами та матрицями у середовищі Google Colab з використанням бібліотеки NumPy